### PR TITLE
Aabedabu/swtpg consolidation coldbox

### LINKED ISSUE #71: Set of the channel state for pedestal value
The setting of the first ADC value (pedestal) for the channel state seems to be wrong as, currently, it takes the same value and it applies it to all the channels.  A fix is already in place in branch `aabedabu/algorithm_testing`. The fix involves a loop through all the registers and channels to extract the ADC value of the first message of a superchunk. 

```sh
// Set the initial state from the window starting at first_msg_p
  template<size_t N>
  void setState(const RegisterArray<N>& first_tick_registers)
  {
    static_assert(N >= NREGISTERS, "Wrong array size");

    // AAA: Loop through all the registers, loop through all the channels, look at the 
    // first message of the superchunk and read the ADC value. This will be used as the 
    // pedestal for the channel state
    for (size_t j = 0; j < NREGISTERS * SAMPLES_PER_REGISTER; ++j) {
      const size_t register_offset = j % SAMPLES_PER_REGISTER; 
      const size_t register_index = j / SAMPLES_PER_REGISTER;
      const size_t register_t0_start = register_index * SAMPLES_PER_REGISTER * FRAMES_PER_MSG;

      int16_t ped;
      for (size_t itime = 0; itime < timeWindowNumFrames; ++itime) {
        const size_t msg_index = itime / 12;
        const size_t msg_time_offset = itime % 12;
        // The index in uint16_t of the start of the message we want. 
        // AAA: 6144 is the sizeof(MessageADCs) which is hardcoded here. TODO: put
        // MessageADCs in a location that can be included and used in the ProcessingInfo 
        const size_t msg_start_index = msg_index * 6144 / sizeof(uint16_t); // NOLINT
        const size_t offset_within_msg = register_t0_start + SAMPLES_PER_REGISTER * msg_time_offset + register_offset;
        const size_t index = msg_start_index + offset_within_msg;

        const uint16_t* input16 = first_tick_registers.data(); // NOLINT

        ped = input16[index];

        break; // breaking in order to select only the first entry
      }

      // Set the pedestals and the 25/75-percentiles: everything else is just the same as in default values
      chanState.pedestals[j] = ped;
      chanState.quantile25[j] = ped - 3;
      chanState.quantile75[j] = ped + 3;
    }
  }
  ```

### LINKED ISSUE #86: SWTPG consolidation developments
After the February coldbox, the SWTPG was updated to better monitor and handle different scenarios. Here is a summary of the main issues encountered:

- Configuration parameter for SWTPG threshold
- Configuration parameter for the SWTPG algorithm selection (threshold-based SWTPG or AbsRS)
- Add support for AbsRS
- Need to monitor - per channel - the rate of TPs 
- Remove the FIR from the threshold-SWTPG algorithm as it was generating too many fake TPs (result from Feb Coldbox)
- Noticed an issue related to the output TPs having long time-over-threshold values 
- Exclude some configurable number of channels based on a static list
- Bug in retrieving the correct channel in the AVX code

### PR DESCRIPTION
**Pull request by adam-abed-abud**
Resolves #86 
Resolves #71 

Summary of fixes: 
- Added  per-channel-monitoring of the TP rates
- Validation of the AbsRS AVX2 implementation. Minor improvements to the initial pedestal values
- Exclusion of channels from the TPHandler using a static list to be added by configuration
- Fix for the TPs with long time over threshold
- Removed the FIR for the threshold-based SWTPG. Code still available in the `tpg` directory
- Configurable parameters: threshold, TPG algorithm selection
- Fix for bug in the AVX code when retrieving the channel number

### CODE REVIEW

File: include/fdreadoutlibs/wib2/WIB2FrameProcessor.hpp [hunk 1]
```diff
@@ -518,49 +583,63 @@ class WIB2FrameProcessor : public readoutlibs::TaskRawDataProcessorModel<types::
...
+            //
+            //TLOG() << "Hit: " << tp_t_begin << " " << offline_channel;
+  
+            triggeralgs::TriggerPrimitive trigprim;
+            trigprim.time_start = tp_t_begin;
+            trigprim.time_peak = (tp_t_begin + tp_t_end) / 2;
+            trigprim.time_over_threshold = int64_t(hit_tover[i]) * clocksPerTPCTick;
+            trigprim.channel = offline_channel;
+            trigprim.adc_integral = hit_charge[i];
+            trigprim.adc_peak = hit_charge[i] / 20;
```
Comment (gcrone) [inline include/fdreadoutlibs/wib2/WIB2FrameProcessor.hpp:612]: Why do we divide by 20 here? Didn't we do a division in the AVX2 code?
Also, why are adc_integral and adc_peak coming from the same variable, surely one is not just 20* the other every time?

File: include/fdreadoutlibs/wib2/tpg/ProcessRSAVX2.hpp [hunk 2]
```diff
@@ -0,0 +1,394 @@
...
+
+inline void
+frugal_accum_update_rs_avx2(__m256i& __restrict__ median,
+                         const __m256i s,
+                         __m256i& __restrict__ accum,
+                         const int16_t acclimit,
+                         const __m256i mask) __attribute__((always_inline));
+
+inline void
+frugal_accum_update_rs_avx2(__m256i& __restrict__ median,
```
Comment (gcrone) [inline include/fdreadoutlibs/wib2/tpg/ProcessRSAVX2.hpp]: Do we need to have 2 frugal accumulator functions? Wouldn't it be better to split it into a separate file and have the 2 process_window functions refer to the same one?

**Comment by gcrone** [comment]
OK, I don't see anything wrong with this.

File: include/fdreadoutlibs/wib2/WIB2FrameProcessor.hpp (hunk 1 above)
Comment (adam-abed-abud) [reply include/fdreadoutlibs/wib2/WIB2FrameProcessor.hpp:612]: Indeed this does not make much sense. This is something that needs to be properly fixed, especially because what we call `time_peak` and `adc_peak` do not actually correspond to what they mean. I created an issue this morning for that #89 . We can do the change later since it requires changing and properly testing the AVX code.

File: include/fdreadoutlibs/wib2/tpg/ProcessRSAVX2.hpp (hunk 2 above)
Comment (adam-abed-abud) [reply include/fdreadoutlibs/wib2/tpg/ProcessRSAVX2.hpp]: Thanks, I'll make the fix shortly

Comment (adam-abed-abud) [reply include/fdreadoutlibs/wib2/tpg/ProcessRSAVX2.hpp]: I pushed a fix for that

File: include/fdreadoutlibs/wib2/WIB2FrameProcessor.hpp (hunk 1 above)
Comment (gcrone) [reply include/fdreadoutlibs/wib2/WIB2FrameProcessor.hpp:612]: OK, makes sense.

**Review by gcrone — APPROVED** [review]
Looks good to me

File: include/fdreadoutlibs/wib2/tpg/ProcessNaive.hpp [hunk 3]
```diff
@@ -83,7 +83,7 @@ process_window_naive(ProcessingInfo<NREGISTERS>& info)
       const size_t msg_index = itime / 12;
       const size_t msg_time_offset = itime % 12;
       // The index in uint16_t of the start of the message we want // NOLINT
-      const size_t msg_start_index = msg_index * sizeof(MessageADCs) / sizeof(uint16_t); // NOLINT
+      const size_t msg_start_index = msg_index * (6144/2) / sizeof(uint16_t); // NOLINT
```
Comment (roland-sipos) [inline include/fdreadoutlibs/wib2/tpg/ProcessNaive.hpp]: Hardcoded size of something.

File: include/fdreadoutlibs/wib2/tpg/ProcessingInfo.hpp [hunk 4]
```diff
@@ -86,19 +96,47 @@ struct ProcessingInfo
...
+        break; // breaking in order to select only the first entry
+      }
+
+      // Set the pedestals and the 25/75-percentiles: everything else is just the same as in default values
       chanState.pedestals[j] = ped;
-      chanState.quantile25[j] = ped - 3;
-      chanState.quantile75[j] = ped + 3;
+      chanState.pedestalsRS[j] = 0;
+      chanState.RS[j] = 0;
+      chanState.quantile25[j] = ped-20;
```
Comment (roland-sipos) [inline include/fdreadoutlibs/wib2/tpg/ProcessingInfo.hpp:138]: What is the -20? Please expand comments about ops. This is very contrary to understand what is happening via the surrodinging member fields and comments? (qiantile25 but ped is substracted by 20. Also comments are talking about 25/75 percentile?

File: include/fdreadoutlibs/wib2/tpg/RegisterToChannelNumber.hpp [hunk 5]
```diff
@@ -25,7 +25,7 @@ namespace swtpg_wib2 {
 struct RegisterChannelMap
 {
   // TODO: Make these the right size
-  uint channel[256];
+  uint channel[128];
```
Comment (roland-sipos) [inline include/fdreadoutlibs/wib2/tpg/RegisterToChannelNumber.hpp]: How did the this change? Should be replaced by const expression.

File: include/fdreadoutlibs/wib2/tpg/RegisterToChannelNumber.hpp [hunk 6]
```diff
@@ -51,7 +51,7 @@ get_register_to_offline_channel_map_wib2(const dunedaq::detdataformats::wib2::WI
   for (size_t ich = 0; ich < dunedaq::detdataformats::wib2::WIB2Frame::s_num_ch_per_frame; ++ich) {
     auto offline_ch = ch_map->get_offline_channel_from_crate_slot_fiber_chan(
       frame->header.crate, frame->header.slot, frame->header.link, ich);
-    TLOG_DEBUG(0) << " offline_ch " << offline_ch; 
+    TLOG_DEBUG(4) << " offline_ch " << offline_ch;
```
Comment (roland-sipos) [inline include/fdreadoutlibs/wib2/tpg/RegisterToChannelNumber.hpp]: Hardcoded debug constant.

**Review by roland-sipos — CHANGES_REQUESTED** [review]
Meanwhile it's a great improvement that there are standalone test applications capable of running the TPG, there are some hardcoded values that should go as const expressions.

File: include/fdreadoutlibs/wib2/tpg/ProcessNaive.hpp (hunk 3 above)
Comment (adam-abed-abud) [reply include/fdreadoutlibs/wib2/tpg/ProcessNaive.hpp]: Removed the hardcoded line and fixed it.

File: include/fdreadoutlibs/wib2/tpg/ProcessingInfo.hpp (hunk 4 above)
Comment (adam-abed-abud) [reply include/fdreadoutlibs/wib2/tpg/ProcessingInfo.hpp:138]: Originally the quantiles were defined as the pedestal values plus or minus 50 (check in the ProtoWIB SWTPG for comparison). With Klaudia, we noticed this was too big as the corresponding threshold value used in the SWTPG (or IQR) becomes 100 for the first ticks. To reduce that value since the RMS is in orders of O(10) we reduced the value of the initial pedestal. Klaudia and I have investigated the appropriate initial values to set in the past but, in the long term, we should make a complete study. 

I added some comments in the code to explain this, let me know if it is clear

File: include/fdreadoutlibs/wib2/tpg/RegisterToChannelNumber.hpp (hunk 5 above)
Comment (adam-abed-abud) [reply include/fdreadoutlibs/wib2/tpg/RegisterToChannelNumber.hpp]: Fixed using the const expression from the TPGConstants file. I noticed we were using arrays of 256 but in practice, we always use only 128. Now it's not hardcoded anymore.

File: include/fdreadoutlibs/wib2/tpg/RegisterToChannelNumber.hpp (hunk 6 above)
Comment (adam-abed-abud) [reply include/fdreadoutlibs/wib2/tpg/RegisterToChannelNumber.hpp]: Removed the hardcoded debug constant.

**Review by roland-sipos — APPROVED** [review]
LGTM

**Review by roland-sipos — APPROVED** [review]
LGTM

**Review by roland-sipos — APPROVED** [review]
LGTM
